import type { Question, ReviewType } from '@/types'

const morning: Question[] = [
  { id: 'morning-1', text: 'What are you grateful for this morning?' },
  { id: 'morning-2', text: 'What is your intention for today?' },
  { id: 'morning-3', text: 'What is the one most important thing to accomplish today?' },
  { id: 'morning-4', text: 'What would make today a great day?' },
  { id: 'morning-5', text: 'What are you looking forward to?' },
  { id: 'morning-6', text: 'Is there anything weighing on your mind?' },
]

const evening: Question[] = [
  { id: 'evening-1', text: 'What were your wins today?' },
  { id: 'evening-2', text: 'What challenged you?' },
  { id: 'evening-3', text: 'What did you learn?' },
  { id: 'evening-4', text: 'How did you show up for the people around you?' },
  { id: 'evening-5', text: 'What will you do differently tomorrow?' },
  { id: 'evening-6', text: 'How would you rate today? (1–10)', type: 'rating' },
]

const weekly: Question[] = [
  { id: 'weekly-1', text: 'What were your biggest accomplishments this week?' },
  { id: 'weekly-2', text: "What didn't get done that you wanted to?" },
  { id: 'weekly-3', text: 'What energized you this week?' },
  { id: 'weekly-4', text: 'What drained you?' },
  { id: 'weekly-5', text: 'What did you learn?' },
  { id: 'weekly-6', text: 'How did your work align with your values and priorities?' },
  { id: 'weekly-7', text: 'Which relationships got attention? Which need more?' },
  { id: 'weekly-8', text: 'Did you maintain the habits you care about?' },
  { id: 'weekly-9', text: 'What surprised you?' },
  { id: 'weekly-10', text: 'What are your top 3 priorities for next week?' },
  { id: 'weekly-11', text: 'Is there anything you need to let go of?' },
  { id: 'weekly-12', text: 'One word to describe this week:' },
]

const monthly: Question[] = [
  { id: 'monthly-1', text: 'What were the highlights of this month?' },
  { id: 'monthly-2', text: 'What were the lowlights?' },
  { id: 'monthly-3', text: 'Did you make progress on your goals? Where did you fall short?' },
  { id: 'monthly-4', text: 'What consumed most of your time?' },
  { id: 'monthly-5', text: 'What consumed most of your energy?' },
  { id: 'monthly-6', text: 'How was your health this month — physical, mental, emotional?' },
  { id: 'monthly-7', text: 'What did you create or build?' },
  { id: 'monthly-8', text: 'What did you learn?' },
  { id: 'monthly-9', text: 'What relationships grew? Which faded?' },
  { id: 'monthly-10', text: 'What financial decisions did you make?' },
  { id: 'monthly-11', text: 'What book, article, or idea had the most impact on you?' },
  { id: 'monthly-12', text: 'What habit did you build or break?' },
  { id: 'monthly-13', text: 'What are you most proud of this month?' },
  { id: 'monthly-14', text: 'What do you wish had gone differently?' },
  { id: 'monthly-15', text: "What's unfinished that needs attention next month?" },
  { id: 'monthly-16', text: 'What do you want to focus on next month?' },
  { id: 'monthly-17', text: 'What are you grateful for this month?' },
  { id: 'monthly-18', text: 'One word or phrase for this month:' },
]

const quarterly: Question[] = [
  { id: 'quarterly-1', text: 'What were your biggest achievements this quarter?' },
  { id: 'quarterly-2', text: 'What were your biggest disappointments?' },
  { id: 'quarterly-3', text: 'Which of your goals from last quarter did you hit?' },
  { id: 'quarterly-4', text: 'Which did you miss, and why?' },
  { id: 'quarterly-5', text: 'How did you grow as a person this quarter?' },
  { id: 'quarterly-6', text: 'What new skills or knowledge did you develop?' },
  { id: 'quarterly-7', text: 'How was your health across all dimensions?' },
  { id: 'quarterly-8', text: 'How were your key relationships?' },
  { id: 'quarterly-9', text: 'What did your finances look like?' },
  { id: 'quarterly-10', text: 'What work or project are you most proud of?' },
  { id: 'quarterly-11', text: "What did you avoid that you shouldn't have?" },
  { id: 'quarterly-12', text: 'What drained your energy consistently?' },
  { id: 'quarterly-13', text: 'What gave you the most energy?' },
  { id: 'quarterly-14', text: 'What themes kept appearing in your life this quarter?' },
  { id: 'quarterly-15', text: 'What do you need to stop doing?' },
  { id: 'quarterly-16', text: 'What do you need to start doing?' },
  { id: 'quarterly-17', text: 'What do you need to do more of?' },
  { id: 'quarterly-18', text: 'What do you need to do less of?' },
  { id: 'quarterly-19', text: 'What is your biggest open loop going into next quarter?' },
  { id: 'quarterly-20', text: 'What does success in the next quarter look like?' },
  { id: 'quarterly-21', text: 'Set 3 goals for next quarter (work, personal, health/relationships):' },
  { id: 'quarterly-22', text: 'What support do you need?' },
  { id: 'quarterly-23', text: 'What are you most excited about next quarter?' },
  { id: 'quarterly-24', text: 'What is a theme or word for next quarter?' },
]

const annual: Question[] = [
  { id: 'annual-1', text: "What did you do this year that you'd never done before?" },
  { id: 'annual-2', text: 'Did you keep your new year\'s resolutions?' },
  { id: 'annual-3', text: 'Did anyone close to you give birth?' },
  { id: 'annual-4', text: 'Did anyone close to you die?' },
  { id: 'annual-5', text: 'What cities/states/countries did you visit?' },
  { id: 'annual-6', text: 'What would you like to have next year that you lacked this year?' },
  { id: 'annual-7', text: 'What date(s) from this year will remain etched upon your memory, and why?' },
  { id: 'annual-8', text: 'What was your biggest achievement of the year?' },
  { id: 'annual-9', text: 'What was your biggest failure?' },
  { id: 'annual-10', text: 'What other hardships did you face?' },
  { id: 'annual-11', text: 'Did you suffer illness or injury?' },
  { id: 'annual-12', text: 'What was the best thing you bought?' },
  { id: 'annual-13', text: 'Whose behavior merited celebration?' },
  { id: 'annual-14', text: 'Whose behavior made you appalled?' },
  { id: 'annual-15', text: 'Where did most of your money go?' },
  { id: 'annual-16', text: 'What did you get really, really, really excited about?' },
  { id: 'annual-17', text: 'What song will always remind you of this year?' },
  { id: 'annual-18', text: 'Compared to this time last year, are you: happier or sadder? Richer or poorer? Healthier or unhealthier?' },
  { id: 'annual-19', text: 'What do you wish you\'d done more of?' },
  { id: 'annual-20', text: 'What do you wish you\'d done less of?' },
  { id: 'annual-21', text: 'How are you spending the holidays?' },
  { id: 'annual-22', text: 'Did you fall in love this year?' },
  { id: 'annual-23', text: "Do you hate anyone now that you didn't hate this time last year?" },
  { id: 'annual-24', text: 'What was your favorite show?' },
  { id: 'annual-25', text: 'What was the best book you read?' },
  { id: 'annual-26', text: 'What was your greatest musical discovery of the year?' },
  { id: 'annual-27', text: 'What was your favorite film?' },
  { id: 'annual-28', text: 'What was your favorite meal?' },
  { id: 'annual-29', text: 'What did you want and get?' },
  { id: 'annual-30', text: 'What did you want and not get?' },
  { id: 'annual-31', text: 'What did you do on your birthday?' },
  { id: 'annual-32', text: 'What one thing would have made your year immeasurably more satisfying?' },
  { id: 'annual-33', text: 'How would you describe your personal fashion this year?' },
  { id: 'annual-34', text: 'What kept you sane?' },
  { id: 'annual-35', text: 'Which celebrity/public figure did you admire the most?' },
  { id: 'annual-36', text: 'What political issue stirred you the most?' },
  { id: 'annual-37', text: 'Who did you miss?' },
  { id: 'annual-38', text: 'Who was the best new person you met?' },
  { id: 'annual-39', text: 'What valuable life lesson did you learn this year?' },
  { id: 'annual-40', text: 'What is a quote that sums up your year?' },
]

export const QUESTIONS: Record<ReviewType, Question[]> = {
  morning,
  evening,
  weekly,
  monthly,
  quarterly,
  annual,
}
